# Generated by Django 2.1.5 on 2019-01-22 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_name', models.CharField(max_length=4, verbose_name='COURSE')),
                ('c_id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='COURSE ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='NAME')),
                ('reg_no', models.CharField(max_length=30, unique=True, verbose_name='REGISTER NO')),
                ('adm_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='ADMISSION NO')),
                ('adrs', models.CharField(max_length=200, verbose_name='ADDRESS')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncas.Course', verbose_name='COURSE')),
            ],
        ),
    ]
