# Generated by Django 2.1.5 on 2019-02-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
