# Generated by Django 2.1.5 on 2019-02-15 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0003_auto_20190215_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncas.Tutor', verbose_name='Tutor'),
        ),
    ]
