# Generated by Django 2.1.5 on 2019-02-15 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0004_auto_20190215_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='sem',
        ),
        migrations.AddField(
            model_name='subject',
            name='sem',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Sem'),
        ),
    ]
