# Generated by Django 2.1.5 on 2019-02-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0005_auto_20190215_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sem',
            field=models.IntegerField(choices=[('Semester 1', 1), ('Semester 2', 2), ('Semester 3', 3), ('Semester 4', 4), ('Semester 5', 5), ('Semester 6', 6)], default=0, verbose_name='Sem'),
        ),
    ]
