# Generated by Django 2.1.5 on 2019-02-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0006_auto_20190215_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sem',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')], default=0, verbose_name='Sem'),
        ),
    ]
