# Generated by Django 2.1.5 on 2019-02-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncas', '0007_auto_20190215_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncas.Subject', verbose_name='Subject'),
        ),
    ]
